const fs = require("fs");
const path = require("path");
const puppeteer = require("puppeteer");
const CMP_SELECTORS_MAP = require("../utils/cmp_selectors_map");
const waitForCmpUi = require("../utils/wait_for_cmp_ui");
const WORD_BOX_TRIGGERS = require("../utils/observatory-corpus/word_box_triggers");

//----------------------------------------------------------------------
//Acknowledgements: Special thanks to Janus for architectural assistance.
//----------------------------------------------------------------------

//files in dependency order
const COM_DIR = path.join(__dirname, "consent-engine");
const COM_FILES = [
    "Tools.js",
    "Matcher.js",
    "Consent.js",
    "Action.js",
    "Detector.js",
    "CMP.js",
    "ConsentEngine.js",
];

/**
 * helper function to iterate all frames and call frameHasBanner for each
 *
 * @param {Page} page - Puppeteer page instance
 * @returns {boolean} heuristicFound - true if frameHasBanner returns true
 */
async function scanAllFramesForBanner(page) {
    let heuristicFound = false;
    for (const frame of page.frames()) {
        if (await frameHasBanner(frame)) {
            heuristicFound = true;
            break;
        }
    }
    return heuristicFound;
}

/**
 * Extracts the target and parent CSS selectors from a rule's showingMatcher detector.
 * Handles both array and object structures generated by the LLM safely.
 *
 * @param {Object} rule - The complete Consent-O-Matic rule object
 * @returns {Object} - Contains matcherTargetSelector (string|null) and matcherParentSelector (string|null)
 */
function findShowingMatcherSelector(rule) {
    let matcherTargetSelector = null;
    let matcherParentSelector = null;
    
    try {
        const showingMatcher = Object.values(rule)[0].detectors[0].showingMatcher;

        const matcher = Array.isArray(showingMatcher) ? showingMatcher[0] : showingMatcher;
        
        matcherTargetSelector = matcher.target ? matcher.target.selector : matcher.selector;
        matcherParentSelector = matcher.parent ? matcher.parent.selector : null;
    } catch (err) {
        console.error("Warning: Could not safely extract showingMatcher from rule.", err.message);
    }

    return { matcherTargetSelector, matcherParentSelector }
}

/**
 * Validates whether the element defined by the showingMatcher is currently visible in the live DOM.
 * Pierces Shadow DOM hosts independently using deep query selection.
 *
 * @param {Page} page - Puppeteer page instance
 * @param {string|null} matcherTargetSelector - The CSS selector of the target element to check
 * @param {string|null} matcherParentSelector - The CSS selector of the parent/host element
 * @returns {Promise<boolean|null>} showingMatcherFound - true if visible, false if hidden/not found, null if no selector provided
 */
async function checkShowingMatcher(page, matcherTargetSelector, matcherParentSelector) {
    if (!matcherTargetSelector) {
        return null;
    }

    return await page.evaluate((targetSel, parentSel) => {

        //querySelectorDeep is copied from my extract_dom.js code
        /**
         * Performs a deep recursive lookup to isolate the first matching element reference 
         * while seamlessly piercing nested Shadow DOM boundaries.
         *
         * @param {string} selector - Functional CSS selector pattern
         * @param {Document|ShadowRoot|HTMLElement} root - Evaluation root
         * @returns {HTMLElement|null} - The discovered element reference, or null
         */
        function querySelectorDeep(selector, root = document) {
            let found = root.querySelector(selector);
            if (found) return found;

            const all = root.querySelectorAll("*");
            for (const el of all) {
                if (el.shadowRoot) {
                    found = querySelectorDeep(selector, el.shadowRoot);
                    if (found) return found;
                }
            }
            return null;
        }

        let searchRoot = document;
        
        if (parentSel) {
            const parentEl = querySelectorDeep(parentSel, searchRoot);

            if (parentEl) {
                searchRoot = parentEl.shadowRoot ? parentEl.shadowRoot : parentEl;
            }
        }

        let element = querySelectorDeep(targetSel, searchRoot);
        if (!element) {
            return false;
        }

        //If the matched element is a Shadow Host, its visibility parameters cannot 
        //be reliably assessed via computedStyle or bounding rectangles. 
        //Returns null to signal an unassessable visual state rather than a false negative.
        //Requires advanced multi-level DOM traversal to fully resolve in future iterations.
        if (element.shadowRoot) {
            return null;
        }

        const style = window.getComputedStyle(element);
        const isVisible = 
            style.display !== "none" && 
            style.visibility !== "hidden" && 
            style.opacity !== "0";
            
        const rect = element.getBoundingClientRect();
        const hasDimensions = rect.width > 0 && rect.height > 0;

        return isVisible && hasDimensions;
        
    }, matcherTargetSelector, matcherParentSelector);
}

/**
 * Evaluates a given frame to determine the presence of an active cookie consent banner.
 * Heavily inspired by the WordBoxGatherer.js mechanics (specifically `findAnchors` and `findWords`).
 * 
 * Source: https://github.com/cavi-au/consent-observatory.eu
 * Copyright (c) 2023 Rolf Bagge, Janus Kristensen
 * Copyright (c) 2024, 2025 Janus Kristensen
 * CAVI, Aarhus University
 * License: MPL 2.0
 * 
 * Modifications (by Simon Pede):
 * - findAnchors: Streamlined to return DOM elements exclusively (omitting path tracking), added 
 * robust null-pointer safeguards, and reads layout properties via `style.zIndex` directly. 
 * - Implemented a geometric filter that discards containers smaller than 10000 pixels to 
 * successfully filter out persistent "revoke/fingerprint" buttons (e.g., Usercentrics).
 * - findWords: Re-architected to accept a pre-compiled regular expression array instead of an 
 * observatory corpus object. Upgraded to fully traverse deep Shadow DOM structures.
 * - Corpus Isolation: The core multilingual word dictionary was extracted, flattened, and decoupled 
 * into an external data module (`wordBoxTriggers`) to preserve separation of concerns.
 * - Anti-Triggers: Implemented a local exclusion dictionary to catch post-consent confirmation states. 
 * This effectively suppresses false positives on websites that dynamically substitute banner content 
 * with confirmation strings instead of tearing down the layout node (e.g., Swedbank). The ones already
 * used by WordBoxGatherer.js are marked.
 * * Execution Strategies:
 * - Structural Traversal: Walks the Light and Shadow DOM hierarchy searching for high-z-index or fixed 
 * positioning elements indicating an overlay layer.
 * - Linguistic Matching: Recursively audits inner text nodes and node attributes against the multilingual 
 * dictionary while validating that no active anti-triggers are present
 *
 * @param {Frame} frame - Puppeteer frame instance
 * @returns {Promise<boolean>} - True if a visual container with matching consent terminology is confirmed
 */
async function frameHasBanner(frame) {
    const antiTriggers = [
        //Experimentally defined indicators to suppress post-consent layout false positives
        "preferences were saved",
        "successfully saved",
        "cookie-success",
        "erfolgreich gespeichert",
        //defined in WordBoxGatherer.js:
        "\\d+ years or older",
        "\\d+ years",
        "\\d+ Jahre oder älter",
        "\\d+ jaar of ouder",
        "\\d+ anni o più",
        "\\d+ ans ou plus",
        "\\d+ anos ou mais"
    ];

    try {
        return await frame.evaluate((triggers, antiTriggers) => {
            //Midas's Anchor Search: Find layout wrappers (including Shadow DOM) (modified)
            function findAnchors(currentElement) {
                if (!currentElement) {
                    return [];
                }
                
                const style = window.getComputedStyle(currentElement);

                if (
                    (style.zIndex && !isNaN(style.zIndex) && parseInt(style.zIndex) > 10) ||
                    (style.position && style.position.includes("fixed"))
                ) {
                    const rect = currentElement.getBoundingClientRect();
                    const isRevokeButton = (rect.width * rect.height) <= 10000;
                    
                    if (isRevokeButton) {
                        return [];
                    }

                    return [currentElement];
                }

                let anchors = [];
                for (let i = 0; i < currentElement.children.length; i++) {
                    anchors = anchors.concat(findAnchors(currentElement.children[i]));
                }
                //scan shadow children
                if (currentElement.shadowRoot) {
                    for (let i = 0; i < currentElement.shadowRoot.children.length; i++) {
                        anchors = anchors.concat(findAnchors(currentElement.shadowRoot.children[i]));
                    }
                }
                return anchors;
            }

            //Midas's Word Search: Recursive search in text-nodes and attributes (modified)
            function findWords(currentElement, triggerRegex, antiTriggerRegex) {
                //ignore parts of page invisible to the user (Midas's original logic)
                if (currentElement.getClientRects().length === 0) {
                    return false;
                }

                let comparisonText = "";
                if (currentElement.attributes) {
                    for (let i = 0; i < currentElement.attributes.length; i++) {
                        comparisonText += currentElement.attributes[i].value + " ";
                    }
                }

                for (let i = 0; i < currentElement.childNodes.length; i++) {
                    if (currentElement.childNodes[i].nodeType === Node.TEXT_NODE) {
                        comparisonText += currentElement.childNodes[i].textContent + " ";
                    }
                }

                if (antiTriggerRegex.test(comparisonText)) {
                    return false; 
                }

                const matches = comparisonText.match(triggerRegex) || [];
                if (matches.length > 0) {
                    return true;
                }

                for (let i = 0; i < currentElement.children.length; i++) {
                    if (findWords(currentElement.children[i], triggerRegex, antiTriggerRegex)) return true;
                }
                
                if (currentElement.shadowRoot) {
                    for (let i = 0; i < currentElement.shadowRoot.children.length; i++) {
                        if (findWords(currentElement.shadowRoot.children[i], triggerRegex, antiTriggerRegex)) return true;
                    }
                }
                
                return false;
            }

            const anchors = findAnchors(document.body);
            const triggerRegex = new RegExp(
                triggers.map(w => "(?:[^\\S\\r\\n]|[\\(\\\"]|^)" + w + "(?:[\\s\\.\\;\\:\\)\\\",]|$)").join("|"), 
                "mgi"
            );

            const antiTriggerRegex = new RegExp(antiTriggers.join("|"), "i");

            for (const anchor of anchors) {
                if (findWords(anchor, triggerRegex, antiTriggerRegex)) {
                    return true;
                }
            }
            return false;
        }, WORD_BOX_TRIGGERS, antiTriggers);
    } catch (err) {
        return false;
    }
}

/**
 * Evaluates the technical and structural state of the host page.
 * Functions as an independent auditor to verify the presence or dismissal
 * of a cookie consent interface based on API responses and layout metrics.
 *
 * 
 * @param {Page} page - The Puppeteer page object
 * @returns {Promise<Object>} bannerStatus data (hasTcfApi, tcfVisible, tcfHidden, scrollLocked)
 */
async function evaluatePageState(page) {
    return await page.evaluate(async () => {
        const bannerStatus = {
            hasTcfApi: false,
            tcfVisible: null,
            tcfHidden: null,
            scrollLocked: false
        };

        //IAB TCF API verification logic adapted from IABJSGatherer.js
        //Source: https://github.com/cavi-au/consent-observatory.eu/blob/master/rules/Gatherers/IABJSGatherer.js
        //Copyright (c) 2023 Rolf Bagge,
        //Copyright (c) 2024, 2025 Janus Kristensen
        //CAVI, Aarhus University
        //License: MPL 2.0
        bannerStatus.hasTcfApi = (window["__tcfapi"] != null);

        if (bannerStatus.hasTcfApi) {
            try {
                const pingResult = await new Promise((resolve) => {
                    const timeoutId = setTimeout(() => {
                        resolve(null);
                    }, 2000);

                    window["__tcfapi"]("ping", 2, (result) => {
                        clearTimeout(timeoutId);
                        resolve(result);
                    });
                });

                if (pingResult) {
                    bannerStatus.tcfVisible = (pingResult.displayStatus === "visible");
                    bannerStatus.tcfHidden = (pingResult.displayStatus === "hidden")
                } else {
                    bannerStatus.error = "API timeout";
                }
            } catch (err) {
                bannerStatus.error = `API error: ${err.message}`;
            }
        }

        //new idea: test if scrolling is blocked on the main page.
        //could be a viable indicator, but i need to test it
        //it does not on work on usercentrics e.g. as they seem to use an isolated overlay
        const bodyStyle = window.getComputedStyle(document.body);
        const htmlStyle = window.getComputedStyle(document.documentElement);
        if (bodyStyle.overflow === "hidden" || bodyStyle.overflowY === "hidden" ||
            htmlStyle.overflow === "hidden" || htmlStyle.overflowY === "hidden") {
            bannerStatus.scrollLocked = true;
        }

        return bannerStatus;
    });
}

/**
 * Compiles, bundles, and instruments the Consent-O-Matic (CoM) extension engine source on the fly.
 * Architectural Rationale:
 * CoM natively utilizes ES modules, which cannot be directly evaluated within isolated browser contexts
 * without introducing heavy compiler wrappers (e.g., Rollup or Webpack). This routine strips module definitions
 * to create a single globally executable script.
 * 
 * Furthermore, since CoM intentionally suppresses interaction errors to optimize end-user experience,
 * this function performs runtime source instrumentation. It injects explicit telemetry hooks into
 * failing DOM selectors, establishing the critical feedback matrix required for the LLM's self-correction loop.
 * 
 * @returns {string} - The fully compiled and instrumented CoM core engine string
 */
function buildComSource() {
    return COM_FILES.map((file) => {
        let content = fs.readFileSync(path.join(COM_DIR, file), "utf8");

        //Remove modern ES module import statements
        content = content.replace(/^import .+$/gm, "");
        //"export default class X" --> "class X"
        content = content.replace(/^export default /gm, "");
        //"export class X {" --> "class X {"
        content = content.replace(/^export /gm, "");

		//CoM natively fails silently to not bother end-users. I patch Action.js 
        //on-the-fly to force explicit console warnings when selectors fail,
        //providing feedback for the LLM's self-correction loop
		if (file === "Action.js") {
            //If a target is missing, inject a warning
            content = content.replace(
                /if\s*\(\s*result\.target\s*!=\s*null\s*\)\s*\{/g, 
                `if (result.target == null) { console.warn("ACTION_TARGET_NOT_FOUND: " + (this.config.target ? this.config.target.selector : "unknown")); } if (result.target != null) {`
            );
            
            //WaitCSS Actions. If the retry timeout is reached, inject a warning into the final "else" block.
            content = content.replace(
                /setTimeout\(checkCss, waitTime\);\s*\}\s*else\s*\{/g,
                `setTimeout(checkCss, waitTime); } else { console.warn("WAITCSS_TIMEOUT: " + (self.config.target ? self.config.target.selector : "unknown")); `
            );
        }

        if (file === "Matcher.js") {
            content = content.replace(
                /throw new Error\("No checkbox found, cannot check state"\);/g,
                `console.warn("ACTION_TARGET_NOT_FOUND: Checkbox Matcher failed for selector: " + (this.config.target ? this.config.target.selector : "unknown")); throw new Error("No checkbox found, cannot check state");`
            );
        }

        return content;
    }).join("\n");
}

/**
 * Executes the instrumented Consent-O-Matic engine within the context of a specific target frame.
 * Orchestrates the full interaction lifecycle using the provided LLM-generated rule configuration.
 *
 * @param {Frame} targetFrame - The specific Puppeteer Frame instance to evaluate
 * @param {Object} rule - The complete rule schema generated for testing
 * @returns {Promise<Object>} - Resolves with the final execution event report from the engine
 */
async function runEngineInFrame(targetFrame, rule) {
    console.error(`Injecting engine into frame: ${targetFrame.url()}`);

    await targetFrame.addScriptTag({ content: comSource });

    //run the test with the rule
    return await targetFrame.evaluate((ruleConfig) => {
        return new Promise((resolve) => {
            //define window.chrome as an empty function because ConsentEngine.js
            //at one point calls chrome.runtime.sendMessage();
            //this would otherwise crash my code as chrome is undefined in puppeteer context
            if (typeof chrome === "undefined") {
                window.chrome = {
                    runtime: {
                        sendMessage: () => {} 
                    }
                };
            }

            ConsentEngine.singleton = null;
            ConsentEngine.generalSettings = { hideInsteadOfPIP: true };
            ConsentEngine.debugValues = {
                "clickDelay": true,
                "skipSubmit": false,
                "paintMatchers": false,
                "debugClicks": true,
                "alwaysForceRulesUpdate": false,
                "skipHideMethod": true,
                "debugLog": true,
                "debugTranslations": false,
                "skipSubmitConfirmation": false,
                "dontHideProgressDialog": true
            };

            ConsentEngine.singleton = new ConsentEngine(ruleConfig, {
                "A": false,
                "B": false,
                "D": false,
                "E": false,
                "F": false,
                "X": false
                }, (evt)=>{
                    resolve(evt);
            });
        });
    }, rule);
}


/**
 * Injected LLM rules can fail at 3 distinct phases.
 *
 * PHASE 1: PARSING & STRUCTURE
 * Trigger: Console error containing "Invalid CMP"
 * Cause: JSON syntax error, missing mandatory fields in matchers,
 * or unsupported action type. CMP class fails to instantiate.
 * Catch: page.on("console")
 *
 * PHASE 2: DETECTION
 * Trigger: Callback payload { handled: false }
 * Causes (based on console logs):
 * - "No CMP detected in 5 seconds...": presentMatcher failed (selector not in DOM)
 * - "[CMP Name] - Not showing": presentMatcher ok, showingMatcher failed (element hidden)
 * - "Found multiple CMPs...": matchers too generic (e.g. bare "div")
 *
 * PHASE 3: EXECUTION
 * Trigger: Callback payload { handled: false, error: true } or 0 clicks
 * Causes (based on console logs):
 * - "Error during consent handling: [Error]": crash during execution
 *   (click target missing, waitcss timeout, infinite loop)
 * - "Consent-O-Matic click count was 0...": engine ran without crashing
 *   but no DOM interactions occurred (selectors missed)
 * 
 * @param {object} rule - JS Object Version of the generated rule by the LLM
 */
async function runTest(rule) {
	console.error("Starting CoM Test Engine...");

	//browser gets initiated exactly as in extract_dom.js
	const browser = await puppeteer.launch({
	    headless: true, //users the more modern headless mode (instead of "shell") --> harder to detect as a bot
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || null,
		args: [
			"--no-sandbox", //important for WSL/Linux
			"--disable-setuid-sandbox", //important for WSL/Linux
			"--disable-blink-features=AutomationControlled", //when chrome is not controlled by an actual user it sets navigator.webdriver = true.
			//CMPs can detect that and block the banner or nerver render it
			"--window-size=1920,1080", //unsure if really necessary, but ensures that puppeteer launches desktop version
			"--lang=en-US,en"
		]
	});

    // Optional non-headless debugging environment configuration:
    // const browser = await puppeteer.launch({
    //     headless: false,
    //     slowMo: 1000,
    //     defaultViewport: null,
    //     args: ["--start-maximized"]
    // });
    const page = await browser.newPage();

	await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36");
	await page.setExtraHTTPHeaders({
		"Accept-Language": "en-US,en;q=0.9"
	});

	await page.evaluateOnNewDocument(() => {
		Object.defineProperty(navigator, "language", {
			get: function() { return "en-US"; }
		});
		Object.defineProperty(navigator, "languages", {
			get: function() { return ["en-US", "en"]; }
		});
	});

	let engineErrors = [];
	let catchNextError = false;

    page.on("console", msg => {
        const type = msg.type();
        const text = msg.text();

		//Sequential error tracking tailored to catch structural groupCollapsed exceptions from ConsentEngine.js
		if (catchNextError && type === "error") {
            engineErrors.push(`Details: ${text}`);
            catchNextError = false;
            return;
        }

		if (text.includes("Invalid CMP")) {
            engineErrors.push(text);
            catchNextError = true;
        } else if (
            text.includes("Error during consent handling") ||
            text.includes("No CMP detected in 5 seconds") ||
            text.includes("Not showing") ||
            text.includes("Found multiple CMPS's")
        ) {
            engineErrors.push(text);
        } else if (text.includes("ACTION_TARGET_NOT_FOUND") || text.includes("WAITCSS_TIMEOUT")) {
			engineErrors.push(`Selector Failed: ${text}`);
		}
    });

    try {
        console.error("Navigating to the page...");
        await page.goto(url, {
            waitUntil: "domcontentloaded",
            timeout: 30000
        });

        console.error("page is loaded!");

        //Blocking Telemetry Barrier: The rich metadata object returned by waitForCmpUi 
        //is intentionally ignored in this test runner context. We leverage this call 
        //exclusively to guarantee that the consent interface is fully inflated and klickable 
        //before extracting baseline metrics. If it times out, we still proceed to allow 
        //the baseline heuristics to independently verify the absence of a banner.
        await waitForCmpUi(page, CMP_SELECTORS_MAP);

        const baselineTcfAndOverlay = await evaluatePageState(page);
        const baselineHeuristic = await scanAllFramesForBanner(page);

        const { matcherTargetSelector, matcherParentSelector } = findShowingMatcherSelector(rule);

        let showingMatcherFoundBaseline = null;
        if (matcherTargetSelector) {
            showingMatcherFoundBaseline = await checkShowingMatcher(page, matcherTargetSelector, matcherParentSelector);
        }

        const baselineState = {
            ...baselineTcfAndOverlay,
            heuristicBannerFound: baselineHeuristic,
            showingMatcherFound: showingMatcherFoundBaseline
        };

        let result = await runEngineInFrame(page.mainFrame(), rule);

        if (!result.handled) {
            console.error("Main frame in testing didnt work! Trying iframes...")
            engineErrors = [];

            const frames = page.frames()
            for (const frame of frames) {
                if(frame === page.mainFrame()) {
                    continue;
                }

                try {
                    const frameUrl = frame.url();
                    if (frameUrl === "about:blank" || frameUrl === "") {
                        continue;
                    }

                    const frameResult = await runEngineInFrame(frame, rule);
                    if (frameResult && frameResult.handled) {
                        result = frameResult;
                        console.error("Success! CMP handled inside iframe.");
                        break;
                    }
                } catch (err) {
                    console.error(`Could not evaluate in frame: ${err.message}`);
                }
            }
        }

        await new Promise(resolve => setTimeout(resolve, 1500));

        let showingMatcherFoundAudit = null;
        if (matcherTargetSelector) {
            showingMatcherFoundAudit = await checkShowingMatcher(page, matcherTargetSelector, matcherParentSelector);
        }

        const auditTcfAndOverlay = await evaluatePageState(page);
        const auditHeuristic = await scanAllFramesForBanner(page);

        const auditState = {
            ...auditTcfAndOverlay,
            heuristicBannerFound: auditHeuristic,
            showingMatcherFound: showingMatcherFoundAudit
        };

        let finalError = result.error ? "Execution error in Consent-O-Matic." : null;
        if (engineErrors.length > 0) {
            finalError = engineErrors.join(" | ");
        } else if (!result.handled) {
            finalError = "Banner not found or matchers failed.";
        }

        let auditScreenshot = null;

        const bannerStillVisible = 
            auditState.heuristicBannerFound === true
            || 
            (auditState.hasTcfApi === true && auditState.tcfVisible === true);
        
        const isDetectorFailure = finalError && finalError.includes("No CMP detected");

        //this logic is more efficient for every day use
        // if (bannerStillVisible && !isDetectorFailure) {
        //     try {
        //         console.error("Validation failed: Banner is still visible. Captures audit screenshot...");
        //         auditScreenshot = await page.screenshot({ encoding: "base64" });
        //     } catch (err) {
        //         console.error("Failed to take audit screenshot:", err.message);
        //     }
        // }

        //EVALUATION MODE: Always capture audit screenshot for vision cross-validation.
        //In production, replace this block with the commented logic above (screenshot
        //only when bannerStillVisible) to improve performance.
        if (!isDetectorFailure) {
            try {
                console.error("Capturing final audit screenshot for vision verification...");
                auditScreenshot = await page.screenshot({ 
                    encoding: "base64",
                    type: "jpeg",
                    quality: 60 
                });
            } catch (err) {
                console.error("Failed to take audit screenshot:", err.message);
            }
        }

        console.log(JSON.stringify({
            handled: result.handled, 
            cmpName: result.cmpName || null, 
            clicks: result.clicks || 0, 
            error: finalError,
            bannerStatus: {
                baseline: baselineState,
                audit: auditState
            },
            auditScreenshot: auditScreenshot
        }));

    } catch (err) {
        console.log(JSON.stringify({ 
            handled: false, 
            cmpName: null, 
            clicks: 0, 
            error: `Puppeteer Error: ${err.message}` 
        }));
    } finally {
        await browser.close();
    }
}

const url = process.argv[2];

if (!url) {
    console.log(JSON.stringify({ error: "Missing argument: url required" }));
    process.exit(1);
}

const comSource = buildComSource();

let ruleJson = "";

process.stdin.setEncoding("utf8");
process.stdin.on("data", chunk => {
    ruleJson += chunk;
});

process.stdin.on("end", () => {
    let rule;
    try {
        rule = JSON.parse(ruleJson);
    } catch (e) {
        console.log(JSON.stringify({ error: "Invalid JSON from Python: " + e.message }));
        process.exit(1);
    }

    console.error(`${JSON.stringify(rule).length}`)

    runTest(rule); 
});